# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: items.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'items.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bitems.proto\x12\x05items\"\x19\n\x0bItemRequest\x12\n\n\x02id\x18\x01 \x01(\x05\" \n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"(\n\x0cItemResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"!\n\x10ItemsAddedResult\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\",\n\x0b\x43hatMessage\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xdc\x01\n\x0bItemService\x12.\n\x0bGetItemById\x12\x12.items.ItemRequest\x1a\x0b.items.Item\x12+\n\x0cListAllItems\x12\x0c.items.Empty\x1a\x0b.items.Item0\x01\x12\x32\n\x08\x41\x64\x64Items\x12\x0b.items.Item\x1a\x17.items.ItemsAddedResult(\x01\x12<\n\x0e\x43hatAboutItems\x12\x12.items.ChatMessage\x1a\x12.items.ChatMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'items_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMREQUEST']._serialized_start=22
  _globals['_ITEMREQUEST']._serialized_end=47
  _globals['_ITEM']._serialized_start=49
  _globals['_ITEM']._serialized_end=81
  _globals['_ITEMRESPONSE']._serialized_start=83
  _globals['_ITEMRESPONSE']._serialized_end=123
  _globals['_EMPTY']._serialized_start=125
  _globals['_EMPTY']._serialized_end=132
  _globals['_ITEMSADDEDRESULT']._serialized_start=134
  _globals['_ITEMSADDEDRESULT']._serialized_end=167
  _globals['_CHATMESSAGE']._serialized_start=169
  _globals['_CHATMESSAGE']._serialized_end=213
  _globals['_ITEMSERVICE']._serialized_start=216
  _globals['_ITEMSERVICE']._serialized_end=436
# @@protoc_insertion_point(module_scope)
